# There is a pre-installed cygwin: http://help.appveyor.com/discussions/suggestions/427-pre-install-cygwin
# But it's old and misses some stuff anyway
shallow_clone: true
cache:
    - c:\cygwin-setup-cache
environment:
    CYGWIN_NOWINPATH: yes
    cygwin_url: https://cygwin.com/setup-x86_64.exe
    matrix:
      - SH: bash
        EXEC: bash
      - SH: dash
        EXEC: dash
      - SH: mksh
        EXEC: ksh
      - SH: zsh
        EXEC: zsh
install:
    - ps: Invoke-WebRequest $env:cygwin_url -OutFile c:\cygwin-setup.exe
    - c:\cygwin-setup.exe --quiet-mode --no-shortcuts --no-startmenu --no-desktop --upgrade-also --only-site --site http://cygwin.mirror.constant.com/ --root c:\cygwin-root --local-package-dir c:\cygwin-setup-cache --packages curl,make,$env:SH
    - c:\cygwin-root\bin\sh -c "`curl -L https://raw.github.com/rylnd/shpec/master/install.sh`"
build_script:
    - c:\cygwin-root\bin\$env:EXEC shpec
