version: "3.0"

services:

  busybox:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.busybox
    volumes:
      - ./:/tmp/wtfc

  ash_alpine: # Almquist Shell https://www.in-ulm.de/~mascheck/various/ash/#busybox
    build:
      context: .
      dockerfile: ./docker/Dockerfile.alpine
      args:
        SHELL_NAME: ash
        SHELL_PKG: # already installed 
    volumes:
      - ./:/tmp/wtfc

  bash_alpine:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.alpine
      args:
        SHELL_NAME: bash
        SHELL_PKG: bash
    volumes:
      - ./:/tmp/wtfc

  bash_debian:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.debian
      args:
        SHELL_NAME: bash
        SHELL_PKG: bash
    volumes:
      - ./:/tmp/wtfc

  dash_alpine:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.alpine
      args:
        SHELL_NAME: dash
        SHELL_PKG: dash@testing
    volumes:
      - ./:/tmp/wtfc

  dash_debian:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.debian
      args:
        SHELL_NAME: bash
        SHELL_PKG: bash
    volumes:
      - ./:/tmp/wtfc

  ksh_alpine:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.alpine
      args:
        SHELL_NAME: mksh
        SHELL_PKG: mksh
    volumes:
      - ./:/tmp/wtfc

  ksh_debian:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.debian
      args:
        SHELL_NAME: ksh
        SHELL_PKG: ksh
    volumes:
      - ./:/tmp/wtfc

  zsh_alpine:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.alpine
      args:
        SHELL_NAME: zsh
        SHELL_PKG: zsh
    volumes:
      - ./:/tmp/wtfc

  zsh_debian:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.debian
      args:
        SHELL_NAME: zsh
        SHELL_PKG: zsh
    volumes:
      - ./:/tmp/wtfc